attackround : 0
deviceno : 0
numusers : 50
isnoniid : 1
isorganized : 1
advratio : 0.5
nrounds : 20
initround : 5
initcut : 0.33
unbiasmech : 0
warfact : 1.25
trainamount :  450
testamount : 50
nepoch : 1
batchsize : 256
lr : 0.0005
minlr : 0.000010
lrschfac: 0.2
applymining : 1
numvals : 3
valdist : "gaussian"
valn : 3
bestth : 0.0001
clipping : 1
clipth : 10
weightdecay : 0.001
momentum :  0.9
seed : 11
useseed : 8
hostilityseed : 90
convertersseed :  51
numofclasses : 3
sparsityratio : 0.3
attack : "collective"
applyarfed : 0
converterdict:
  0: 1
  1: 2
  2: 0