deviceno : 0
nrounds : 20
attackround : 0
initround : 5
numusers : 100
isnoniid : 1
advratio : 0.5
isorganized : 1
unbiasmech : 0
applymining : 1
numvals : 4
valdist : "uniform"
valn : 10
warfact : 0.25
initcut : 0.17
trainamount :  4000
testamount : 890
nepoch : 50
batchsize : 256
lr : 0.001  
momentum : 0.9
iscnn : 0
seed : 1
useseed : 23
hostilityseed : 77
convertersseed :  51
numofclasses : 10
sparsityratio : 0.2
attack : "collective"
applyarfed : 0
converterdict: 
  0: 9
  1: 7
  2: 5
  3: 8
  4: 6
  5: 2
  6: 4
  7: 1
  8: 3
  9: 0